version: "4.0"
services:
  app:
    build:
      context: . 
      dockerfile: ./server.Dockerfile
    restart: always
    volumes:
      - .:.
    ports:
      - "8080:8080"
    expose:
      - 8080
  db:
    build: 
      context: .
      dockerfile: ./db.Dockerfile
    restart: always
    volumes:
      - .:.
    ports:
      - "5000:5000"
    expose:
      - 5000
  client:
    build: ./frontend/ai
    restart: always
    volumes:
      - "./frontend/ai/public/data:/usr/share/nginx/html/public/data"
    ports:
      - "3000:80"
    depends_on:
      - app
      - db
