version: "4.0"
services:
  app:
    build:
      context: . 
      dockerfile: ./server.Dockerfile
    restart: always
    volumes:
      - .:/app/AIC2024
    ports:
      - "8080:8080"
    expose:
      - 8080
  # db:
  #   build: 
  #     context: .
  #     dockerfile: ./db.Dockerfile
  #   restart: always
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "5000:5000"
  #   expose:
  #     - 5000
